/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FlowProRouteImport } from './routes/flow-pro'
import { Route as PaceProRouteImport } from './routes/pace-pro'
import { Route as StoreProRouteImport } from './routes/store-pro'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowProRoute = FlowProRouteImport.update({
  id: '/flow-pro',
  path: '/flow-pro',
  getParentRoute: () => rootRouteImport,
} as any)
const PaceProRoute = PaceProRouteImport.update({
  id: '/pace-pro',
  path: '/pace-pro',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreProRoute = StoreProRouteImport.update({
  id: '/store-pro',
  path: '/store-pro',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/flow-pro': typeof FlowProRoute
  '/pace-pro': typeof PaceProRoute
  '/store-pro': typeof StoreProRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/flow-pro': typeof FlowProRoute
  '/pace-pro': typeof PaceProRoute
  '/store-pro': typeof StoreProRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/flow-pro': typeof FlowProRoute
  '/pace-pro': typeof PaceProRoute
  '/store-pro': typeof StoreProRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/flow-pro' | '/pace-pro' | '/store-pro'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/flow-pro' | '/pace-pro' | '/store-pro'
  id: '__root__' | '/' | '/flow-pro' | '/pace-pro' | '/store-pro'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FlowProRoute: typeof FlowProRoute
  PaceProRoute: typeof PaceProRoute
  StoreProRoute: typeof StoreProRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flow-pro': {
      id: '/flow-pro'
      path: '/flow-pro'
      fullPath: '/flow-pro'
      preLoaderRoute: typeof FlowProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pace-pro': {
      id: '/pace-pro'
      path: '/pace-pro'
      fullPath: '/pace-pro'
      preLoaderRoute: typeof PaceProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store-pro': {
      id: '/store-pro'
      path: '/store-pro'
      fullPath: '/store-pro'
      preLoaderRoute: typeof StoreProRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FlowProRoute: FlowProRoute,
  PaceProRoute: PaceProRoute,
  StoreProRoute: StoreProRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
